function result = objfun(data, p0, phi_smc, model, nobs)
        t0 = 1;

    [ctou,clandaw,cg,curvp,curvw,cgamma,cbeta,cpie,ctrend,constebeta,...
      constepinf,constelab,calfa,csigma,cfc,cgy,csadjcost,chabb,cprobw,...
      csigl,cprobp,cindw,cindp,czcap,crpi,crr,cry,crdy,...
      crhoa,crhob,crhog,crhoq,crhom,crhop,crhow,...
      cmap,cmaw,clandap,cbetabar,cr,crk,cw,cikbar,cik,clk,...
      cky,ciy,ccy,crkky,cwhlc,cwly,...
      cstda,cstdb,cstdq,cstdm,cstdg,cstdp,cstdw,...
      eta,...
      a,b,qs,ms,g,spinf,sw,epinfma,ewma,...
      invefl,cfl,yfl,invel,cl,pinfl,wl,yl,rl,...
      kpf,kp,...
      a_p,b_p,qs_p,ms_p,g_p,spinf_p,sw_p,...
      epinfma_p,ewma_p,...
      invefl_p,cfl_p,yfl_p,...
      invel_p,cl_p,pinfl_p,wl_p,yl_p,rl_p,...
      kpf_p,kp_p,...
      rkf,wf,zcapf,labf,kkf,invef,pkf,rrf,yf,cf,...
      mc,rk,w,zcap,lab,kk,inve,pk,r,pinf,yy,c,...
      rkf_p,wf_p,zcapf_p,labf_p,kkf_p,invef_p,pkf_p,rrf_p,yf_p,cf_p,...
      mc_p,rk_p,w_p,zcap_p,lab_p,kk_p,inve_p,pk_p,r_p,pinf_p,y_p,c_p] =...
      SW_model_ss;
    
%     for ii = 1:model.ns
%         PAR(model.estimation(ii)) = p0(ii);
%     end
    for i = 1:model.ns
        sfg = strcat(genvarname(model.estimate(i,:)),' = p0(',string(i),');');
        eval(sfg) 
    end
    
    SW_num_eval;
    eta = nETASHOCK;
    
    %First-order approximation
    [sol_mat.gx, sol_mat.hx, sol_mat.qzflag] = gx_hx(nfy,nfx,nfyp,nfxp);
    
    if model.flag_order > 1
        %Second-order approximation
        [sol_mat.gxx,sol_mat.hxx] = gxx_hxx(nfx,nfxp,nfy,nfyp,nfypyp,nfypy,nfypxp,nfypx,nfyyp,nfyy,nfyxp,nfyx,nfxpyp,nfxpy,nfxpxp,nfxpx,nfxyp,nfxy,nfxxp,nfxx,sol_mat.hx,sol_mat.gx); 
        [sol_mat.gss,sol_mat.hss] = gss_hss(nfx,nfxp,nfy,nfyp,nfypyp,nfypy,nfypxp,nfypx,nfyyp,nfyy,nfyxp,nfyx,nfxpyp,nfxpy,nfxpxp,nfxpx,nfxyp,nfxy,nfxxp,nfxx,sol_mat.hx,sol_mat.gx,sol_mat.gxx,eta);
    end
    
    if sol_mat.qzflag == 1
        result = kf(data, sol_mat.hx, eta*eta', zeros(nobs, 1), eye(nobs, model.ny) * sol_mat.gx, 0.0001 * eye(nobs), t0);
    else
        result = -10000000000.0;
    end
end